# Generated by Django 5.1.2 on 2024-10-13 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('degree', models.CharField(max_length=255)),
                ('college_name', models.CharField(max_length=255)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('Department', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('guide_name', models.CharField(max_length=255)),
                ('guide_designation', models.CharField(max_length=255)),
                ('guide_location', models.CharField(max_length=255)),
                ('guide_co_name', models.CharField(max_length=255)),
                ('guide_co_designation', models.CharField(max_length=255)),
                ('guide_co_location', models.CharField(max_length=255)),
                ('date', models.DateField()),
            ],
        ),
    ]
